sweety/config/routes.rb
Rails.application.routes.draw do
  resources :blood_glucose_levels
  resources :users

   root 'users#login'
   match '/login' => 'users#login', via: [:get, :post]
    match '/logout' => 'users#logout', via: [:get, :post]
   match '/autheticate' => 'users#autheticate', via: [:get, :post]
   get '/home' => 'home#home'
   match '/create' => 'users#create', via: [:get, :post]
   match '/reports' => 'blood_glucose_levels#reports', via: [:get, :post]
   match '/home' => 'home#home', via: [:get, :post]
   match 'fetch_report' => 'blood_glucose_levels#fetch_report', via: [:get, :post]

end

sweety/app/models/blood_glucose_level.rb
class BloodGlucoseLevel < ActiveRecord::Base
	belongs_to :patient
end

sweety/app/models/doctor.rb
class Doctor < ActiveRecord::Base
	#belongs_to :user, :as => :account
end

sweety/app/models/patient.rb
class Patient < ActiveRecord::Base
		#belongs_to :user, :as => :account
		#has_one :blood_glucose_level
end

sweety/app/models/user.rb
class User < ActiveRecord::Base
	#belongs_to :account, :polymorphic => true
end

sweety/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  #protect_from_forgery with: :exception

  protect_from_forgery
  skip_before_action :verify_authenticity_token, :only => [:login,:autheticate]
  
  # Overload handle_unverified_request to ensure that
  # exception is raised each time a request does not
  # pass validation.
  def handle_unverified_request
    raise(ActionController::InvalidAuthenticityToken)
  end
end

sweety/app/controllers/blood_glucose_levels_controller.rb
class BloodGlucoseLevelsController < ApplicationController
  before_action :set_blood_glucose_level, only: [:show, :edit, :update, :destroy]

  # GET /blood_glucose_levels
  def index
    @blood_glucose_levels = BloodGlucoseLevel.all
  end

  # GET /blood_glucose_levels/1
  def show
  end

  # GET /blood_glucose_levels/new
  def new
    @blood_glucose_level = BloodGlucoseLevel.new

  end

  # GET /blood_glucose_levels/1/edit
  def edit
  end

  # POST /blood_glucose_levels
  def create
      @from_date = Date.today.to_date.strftime("%Y-%m-%d")
      id = params[:blood_glucose_level][:patient_id]

      @patient_glucose_record = BloodGlucoseLevel.where(["patient_id=? and date(created_at)=?",id,@from_date])

      if @patient_glucose_record.count >= 4
        flash[:notice] = "Entry is over for the day to this patient"
        redirect_to :action => "new", notice: 'Entry is over for the day to this patient.'     
      else
        @blood_glucose_level = BloodGlucoseLevel.new(blood_glucose_level_params)
        if @blood_glucose_level.save
          redirect_to @blood_glucose_level, notice: 'Blood glucose level was successfully created.'
        else
          render :new
        end
      end
  end


  #Report View
  def reports

  end

  #Generate Reports
  def fetch_report
    session[:patient_id] = params[:patient_name] if session[:account] == "Doctor"
    date = params[:date].to_date
    report = params[:report]
    @daily_date = date.strftime("%Y-%m-%d")
    @month = date.strftime("%m")
    @begining = date.beginning_of_month.strftime("%Y-%m-%d")
    @patientname = Patient.find(session[:patient_id]).name
    @bloodgroup = Patient.find(session[:patient_id]).bloodgroup


    case report
    when  "Daily"
      @records =  BloodGlucoseLevel.where(["patient_id=? and date(created_at)=?", session[:patient_id] , @daily_date.to_date()])
    when "Monthly"
      @records =  BloodGlucoseLevel.where(["patient_id=? and extract(month from created_at)=?", session[:patient_id] , @month])
    else
      @records =  BloodGlucoseLevel.where(["created_at BETWEEN ? AND ?", @begining, @daily_date.to_date()])
    end

    render :layout=> false
  end

  # PATCH/PUT /blood_glucose_levels/1
  def update
    if @blood_glucose_level.update(blood_glucose_level_params)
      redirect_to @blood_glucose_level, notice: 'Blood glucose level was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /blood_glucose_levels/1
  def destroy
    @blood_glucose_level.destroy
    redirect_to blood_glucose_levels_url, notice: 'Blood glucose level was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blood_glucose_level
      @blood_glucose_level = BloodGlucoseLevel.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def blood_glucose_level_params
      params.require(:blood_glucose_level).permit(:patient_id, :glucose_level)
    end
end

sweety/app/controllers/home_controller.rb
class HomeController < ApplicationController

	def home

	end
end

sweety/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  def index
    @users = User.all
  end

  # GET /users/1
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create

    if params[:account][:type] == "Patient"
      @patient = Patient.new(:name=>params[:first_name]+params[:last_name],:address=>params[:address],:email=>params[:email],:phone=>params[:phone],:bloodgroup=>params[:patient][:bloodgroup])
      @patient.save
      @res = @patient.id
    else
      @doctor = Doctor.new(:name=>params[:first_name]+params[:last_name],:address=>params[:address],:email=>params[:email],:phone=>params[:phone])
      @doctor.save
      @res = @doctor.id
    end

    @user = User.new(:account_id=> @res,:username=>params[:username], :password=>params[:password],:account_type=>params[:account][:type])

    if @user.save
      redirect_to :action=>"login", notice: 'User was successfully created.'
    else
      redirect_to :action=>"login", notice: 'Error while registering the Patient/Doctor'
    end
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  def login
    
  end

  def logout
    session.clear
    redirect_to :action=>"login"
  end

  def autheticate
    user = User.find_by username: params[:username]
    if user && user.password ==  params[:password]
      user    
      redirect_to :controller=>"home" , :action=>"home" 
      session[:username] = user.username
      if user.account_type == "Patient"
        session[:account] = "Patient"
        session[:patient_id] = user.account_id
      else
        session[:account] = "Doctor"
        session[:doctor_id] = user.account_id
      end
    else
      flash[:notice] = "Invalid Username or Password"
      redirect_to :action=>"login"
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def user_params
      params.require(:user).permit(:account_id,:username, :password, :account_type)
    end
end

sweety/app/helpers/application_helper.rb
module ApplicationHelper
end

sweety/app/helpers/blood_glucose_levels_helper.rb
module BloodGlucoseLevelsHelper
end

sweety/app/helpers/users_helper.rb
module UsersHelper
end

sweety/app/views/blood_glucose_levels/_form.html.erb
<%= form_for(@blood_glucose_level) do |f| %>
  <% if @blood_glucose_level.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blood_glucose_level.errors.count, "error") %> prohibited this blood_glucose_level from being saved:</h2>

      <ul>
      <% @blood_glucose_level.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<br>
<br>
  <div class="row">
    <%= f.label :patient_id %>
    <%= f.select :patient_id, Patient.select("id, name").collect {|p| [ p.name, p.id ] } %>
  </div>
  <div class="row">
    <%= f.label :glucose_result %>
    <%= f.number_field :glucose_level , :min => 1, :max => 999 %><b>mg/dl</b>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<style type="text/css">
  .h1, h1 {
      font-size: 25px;
  }
  input[type="number"]{
        height: 30px;
      width: 19%;
      margin-left: -1%;
      margin-top: 2%;
  }
  label,button, input, select, textarea {
    display: inline;
  }
  label {
      display: inline;
      margin-right: 5%;
      text-align: right;
      float: none;
  }
  input[type=submit]{
    margin-top: 5%
  }
</style>

sweety/app/views/blood_glucose_levels/edit.html.erb
<h1>Editing Blood Glucose Level</h1>

<%= render 'form' %>

<%= link_to 'Show', @blood_glucose_level %> |
<%= link_to 'Back', blood_glucose_levels_path %>

sweety/app/views/blood_glucose_levels/fetch_report.html.erb
<Div class= "row" id="name">
<label>Name :  </label> <%=@patientname%> 
</Div>

<Div class= "row" id="bloodgroup">
<label>Blood Group :  </label>  <%=@bloodgroup%></Div>
<table class="pure-table">

<thead>
<th>Date</th>
<th>Glucose level</th>
</thead>
<tbody>
<% @records.each_with_index do |record, index|%>

<tr>

<td><%= record.created_at %></td>

<td><%= record.glucose_level %></td>
<tr>
<% end %>
  </tbody>
</table>

<style>
#name{
	float: left; width: 25%;
	    font-size: larger;
        color: #3973e3;
    font-weight: bold;
}
#bloodgroup{
	float: right;width: 25%;
	    font-size: larger;
        color: #3973e3;
    font-weight: bold;
}

</style>

sweety/app/views/blood_glucose_levels/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Blood Glucose Levels</h1>

<table>
  <thead>
    <tr>
      <th>Patient</th>
      <th>Glucose level</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blood_glucose_levels.each do |blood_glucose_level| %>
      <tr>
        <td><%= blood_glucose_level.patient_id %></td>
        <td><%= blood_glucose_level.glucose_level %></td>
        <td><%= link_to 'Show', blood_glucose_level %></td>
        <td><%= link_to 'Edit', edit_blood_glucose_level_path(blood_glucose_level) %></td>
        <td><%= link_to 'Destroy', blood_glucose_level, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blood glucose level', new_blood_glucose_level_path %>

sweety/app/views/blood_glucose_levels/new.html.erb
<h1>Enter Blood Glucose Level</h1>
<p id="notice"><%= notice %></p>
<%= render 'form' %>

<%#= link_to 'Back', blood_glucose_levels_path %>

sweety/app/views/blood_glucose_levels/reports.html.erb
<div id="reports">

<div class="row">
 <% if session[:account] == "Doctor" %>
	<label>Report By :  </label>
	<%=select 'patient','name', Patient.select("id, name").collect {|p| [ p.name, p.id ] }%>
 <% end %>
	<label>Report By :  </label>
	<%=select  'report','reportoption',[["Daily"],["Monthly"],["Month To Date"]]%>

	  <label>Date :  </label>
	  <input type="text" id="datepicker">

	  <button type="button" onclick="fetchreport()">Generate Report</button>
</div>

<div class="row" id = "displayreports">

</div>

<div>

<style type="text/css">
	.row{
		margin: 1%
	}
	label{
		display: inline;
		margin-left: 2%
	}
	input[type="text"]{
	height: 32px;
    margin-top: 12px;
	}
	button{
		margin-left: 2%;
	}

</style>

<script>

jQuery(function(){
jQuery( "#datepicker" ).datepicker();
jQuery( "#datepicker" ).datepicker({ dateFormat: 'yy-mm-dd' });
});


	function fetchreport(){
		var date1 = jQuery("#datepicker").datepicker({ dateFormat: "yy-mm-dd" }).val();
		var d = new Date(date1);
		var curr_date = d.getDate();
		var curr_month = d.getMonth() + 1; //Months are zero based
		var curr_year = d.getFullYear();
		var date = (curr_year + "-" + curr_month + "-" + curr_date);
		var patient_name = jQuery("#patient_name").val();

		alert(patient_name);
		 var report = jQuery( "#report_reportoption" ).val();
		 if (date1 != ""){
		 	jQuery.ajax({
		 		url: "fetch_report", 
		 		data:{report:report, date:date, patient_name:patient_name},
		 		success: function(result){
		        jQuery("#displayreports").html(result);
		    }});
		 } else {
		 	alert("Please select the date...");
		 }

	}
</script>

sweety/app/views/blood_glucose_levels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Patient:</strong>
  <%= @blood_glucose_level.patient_id %>
</p>

<p>
  <strong>Glucose level:</strong>
  <%= @blood_glucose_level.glucose_level %>
</p>

<%= link_to 'Edit', edit_blood_glucose_level_path(@blood_glucose_level) %> |
<%= link_to 'Back', blood_glucose_levels_path %>

sweety/app/views/home/home.html.erb
<Div class="row" style="font-size: xx-large;margin-top:5%"> Welcome to Sweety</Div>

sweety/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sweety</title>
  <%= stylesheet_link_tag    'application' , media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= stylesheet_link_tag "bootstrap.min.css" %> 
  <%= stylesheet_link_tag "bootstrap-responsive.css" %>
  <%= javascript_include_tag 'bootstrap.min.js' %>
  <%= javascript_include_tag 'jquery-3.2.1.js'%>
  <%= javascript_include_tag 'jquery-ui.js'%>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  <%= csrf_meta_tags %>
</head>

<body>
<% if (session[:username] != nil) %>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">SWEETY - Diabetes Tracker</a>
    </div>
    <ul class="nav navbar-nav">
      <li> <a href="/home" >Home</a></li>
      <% if session[:account] != "Doctor" %>
      <li><a href="/blood_glucose_levels/new" >Record</a></li>
      <% end %>
      <li><a href="/reports" >Reports</a></li>
      <li><a href="/logout" >Logout</a></li>
    </ul>
  </div>
</nav>


  <% end %>
<div class="container">
  <%= yield %>
</div>


</body>
</html>

sweety/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_area :username %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_area :password %>
  </div>
  <div class="field">
    <%= f.label :account_type %><br>
    <%= f.text_area :account_type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

sweety/app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

sweety/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Password</th>
      <th>Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.password %></td>
        <td><%= user.type %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

sweety/app/views/users/login.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sweety</title>
  <%= stylesheet_link_tag "bootstrap" %> 
  <%= stylesheet_link_tag "bootstrap-responsive" %>
  <%= javascript_include_tag 'bootstrap' %>
  <%= javascript_include_tag 'jquery-3.2.1'%>
  <%= javascript_include_tag 'jquery-ui'%>

  <%= csrf_meta_tags %>
</head>

<body>
<div class="container">
	<div class="row">
        <div class="span12">
    		<div class="" id="loginModal">
              <div class="modal-header">
              <p id="notice" style="color:red"><%= notice %></p>
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h3>Welcome to SWEETY - Diabetes Tracker</h3>
              </div>
              <div class="modal-body">
                <div class="well">
                  <ul class="nav nav-tabs">
                    <li class="active"><a href="#login" data-toggle="tab">Login</a></li>
                    <li><a href="#create" data-toggle="tab">Create Account</a></li>
                  </ul>
                  <div id="myTabContent" class="tab-content">
                    <div class="tab-pane active in" id="login">
                      <form class="form-horizontal" action='autheticate' method="POST">
                        <fieldset>
                          <div id="legend">
                            <legend class="">Login</legend>
                          </div>    
                          <div class="control-group">
                            <!-- Username -->
                            <label class="control-label"  for="username">Username</label>
                            <div class="controls">
                              <input type="text" id="username" name="username" placeholder="" class="input-xlarge" required>
                            </div>
                          </div>
     
                          <div class="control-group">
                            <!-- Password-->
                            <label class="control-label" for="password">Password</label>
                            <div class="controls">
                              <input type="password" id="password" name="password" placeholder="" class="input-xlarge" required>
                            </div>
                          </div>
     
     
                          <div class="control-group">
                            <!-- Button -->
                            <div class="controls">
                              <button class="btn btn-success">Login</button>
                            </div>
                          </div>
                        </fieldset>
                      </form>                
                    </div>
                    <div class="tab-pane fade" id="create">

                    <%= form_tag('/create', :method=>'post', :multipart => true) do %>
                    <div class="main col-lg-9 myHalfCol">
                        <div class="col-lg-6">
                        <label>Username</label>
                        <%= text_field_tag :username, '', :class=>"input-xlarge"%><br />
                        <label>First Name</label>
                        <%= text_field_tag :first_name, '',:class=>"input-xlarge"%><br />
                        <label>Last Name</label>
                        <%= text_field_tag :last_name, '',:class=>"input-xlarge"%><br />
                        <label>Password</label>
                        <%= text_field_tag :password, '', :class=>"input-xlarge"%><br />
                        <label>Email</label>
                        <%= text_field_tag :email, '',:class=>"input-xlarge"%><br />
                        </div>

                        <div class="col-lg-6">
                        <label>Address</label>
                        <%= text_field_tag :address, '',:class=>"input-xlarge"%><br />
                        <label>Phone Number</label>
                        <%= text_field_tag :phone, '',:class=>"input-xlarge"%><br />                    
                        <label>Account Type</label>
                        <%= select "account","type", [['Patient', 'Patient'],['Doctor', 'Doctor']], :html_options=>{:onChange=>"showbloodgroup();"} %>
                        <label>Blood Group</label>
                        <%= select  'patient','bloodgroup',[["B-"],["B+"],["O+"],["O-"],["A+"],["A-"],["AB+"],["AB-"]]%>
                        <br>
                        <%= submit_tag 'Submit' %>
                        <% end %>
                        </div>
                    </div>
                    </div>
                </div>
              </div>
            </div>
        </div>
	</div>
</div>
</div>
</body>
</html>

<style>
  .modal-body {
    max-height: 700px;
}
input[type="text"], input[type="password"]{
  height: 10%;
}
select {
    width: 270px;
    }
</style>

<script>

  function showbloodgroup()
  {
    var account_type = jQuery("#account_type").val()
    alert(account_type);
    if (account_type == "Doctor"){
      jQuery("#patient_bloodgroup").hide();
    } else {
      jQuery("#patient_bloodgroup").show();
    }
  }
</script>

sweety/app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

sweety/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<p>
  <strong>Type:</strong>
  <%= @user.account_type %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>